Fixed maxsatz2009 warning implicit declaration order (#67)
In case of a mac, the maxsatz binary which is used for the MPE task is compiled from source during setup/installation. The source code maxsatz2009.c:2394:2 contained an implicit declaration of function treat_complementary_unitclauses, causing an error when compiling with C99.